spring:
  cloud:
    gcp:
      maps-api-key:
        location: classpath:./config/mapsAPIKey.txt
      project-id: timetablegenerator-e55f3
      firestore:
        credentials:
          location: classpath:./config/serviceAccountKey.json