name: build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [ opened, edited, reopened, synchronize ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    permissions:
      contents: 'write'
      pull-requests: 'write'
      id-token: 'write'
      packages: write
    steps:

      # Check out your GitHub repo into the container executing these steps
      - name: "Cloning repo"
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Maven Build
        run: |
          mkdir -p src/main/resources/config
          echo "${{ secrets.GCP_SECRET_KEY }}" > src/main/resources/config/serviceAccountKey.json
          mvn clean package